/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  albanian: {
    dashboard: 'Paneli',
    aiAssistant: 'Asistenti AI',
    aiAssistantTitle: 'Asistenti AI për Trafikun',
    aiPoweredBy: 'Fuqizuar nga Groq',
    settings: 'Konfigurimet',
    trafficCommandCenter: 'Qendra e komandës së trafikut',
    totalReports: 'Total raportet',
    totalItems: 'gjithsej',
    active: 'Aktiv',
    cleared: 'Pastruar',
    underControl: 'Nën kontroll',
    reportIncident: 'Raporti i incidentit',
    createNewTrafficAlert: 'Krijo një alarm trafiku të ri',
    editMode: 'Modaliteti i redaktimit',
    newReport: 'Raport i ri',
    incidentTitle: 'Titulli i incidentit',
    enterTitle: 'Mbyllja e rrugës në M4',
    category: 'Kategoria',
    description: 'Përshkrimi',
    addDetails: 'Shto detaje për incidentin dhe përgjigjen e rekomanduar.',
    loginTitle: 'Qendra e Komandës së Trafikut',
    loginSubtitle: 'Hyni për të menaxhuar raportet e incidenteve dhe monitoruar kushtet e rrugëve.',
    loginButton: 'Hyni në Kontroll',
    loginSigningIn: 'Duke hyrë...',
    loginNoAccount: 'I ri për Komandën e Trafikut?',
    loginSignupLink: 'Krijoni një llogari',
    signupTitle: 'Bashkohuni me Komandën e Trafikut',
    signupSubtitle: 'Krijoni një llogari të sigurt për të menaxhuar incidentet dhe shikuar kushtet e rrugëve.',
    signupButton: 'Krijo llogari',
    signupCreatingAccount: 'Duke krijuar llogari...',
    signupAlreadyHaveAccount: 'Keni një llogari tashmë?',
    signupLoginLink: 'Hyni këtu',
    close: 'Mbyll',
    fullName: 'Emri i plotë',
    email: 'Email',
    emailAddress: 'Adresa email',
    passwordLabel: 'Fjalëkalimi',
    confirmPassword: 'Konfirmo fjalëkalimin',
    tryAgain: 'Provo përsëri',
    signupSuccess: 'Llogaria u krijua me sukses. Po ridrejtoheni në hyrje...',
    selectLocation: 'Zgjidh një vendndodhje në hartë',
    clickMapToPlacePin: 'Kliko në hartë për të vendosur pin-in tuaj',
    locationSelected: 'Vendndodhja e zgjedhur',
    severity: 'Rëndësia',
    status: 'Statusi',
    addIncident: 'Shto incidentin',
    updateReport: 'Përditëso raportin',
    cancelEdit: 'Anulo redaktimin',
    recentIncidents: 'Incidentet e fundit',
    reportFlow: 'Rrjedha e raporteve',
    noReports: 'Ende nuk ka raporte incidenti. Përdor formularin për të shtuar një dhe monitoro kushtet e trafikut.',
    edit: 'Redakto',
    delete: 'Fshi',
    confirm: 'Fshi këtë raport incidenti?',
    titleRequired: 'Titulli është i nevojshëm.',
    offline: 'Jeni offline. Kontrolloni lidhjen tuaj të internetit dhe provoni përsëri.',
    timeout: 'Kërkesa ka skaduar. Provoni përsëri.',
    networkError: 'Problem me lidhjen. Kontrolloni internetin dhe provoni përsëri.',
    successMessage: 'Raporti juaj u regjistrua me sukses.',
    updateSuccess: 'Incidenti u përditësua me sukses.',
    deleteSuccess: 'Incidenti u hoq nga paneli yt.',
    errorSave: 'Nuk mund të ruhet incidenti.',
    errorUpdate: 'Nuk mund të përditësohet incidenti në Supabase.',
    errorDelete: 'Nuk mund të hiqet incidenti nga Supabase.',
    errorFetch: 'Nuk mund të ngarkohen raportet nga Supabase.',
    liveTrafficMap: 'Harta e trafikut live',
    currentOperations: 'Operacionet aktuale',
    trafficOverview: 'Pamja e përgjithshme e rrjedhës së trafikut',
    affectedCorridor: 'Korridori më i prekur',
    mainIncident: 'Incidenti kryesor',
    systemHealth: 'Shëndeti i sistemit',
    route: 'Rruga I-95',
    heavyTrafficDescription: 'Shumë vonesa për shkak të mbylljes së korsisë dhe trafikut të rëndë.',
    northHub: 'Aksident në Veri Hub',
    responseTeam: 'Ekipi i përgjigjes u dërgua. Pastrimi i parashikuar në 45 min.',
    stable: 'Stabil',
    allSystems: 'Të gjitha sistemet e monitorimit po funksionojnë normalisht.',
    saving: 'Duke ruajtur...',
    noDetails: 'Nuk janë dhënë detaje shtesë.',
    retry: 'Duke provuar përsëri...',
    personalizeExperience: 'Personalizo përvojën tënde',
    theme: 'Tema',
    light: 'Dritë',
    lightTheme: 'Mënyra e ndritshme',
    dark: 'Errësirë',
    darkTheme: 'Mënyra e errët',
    language: 'Gjuha',
    albanian: 'Shqip',
    english: 'Anglisht',
    notifications: 'Njoftime',
    enable: 'Aktivizo',
    disable: 'Çaktivizo',
    autoSave: 'Ruajtja automatike',
    notificationsInfo: 'Merrni njoftime për incidente të reja',
    autoSaveInfo: 'Ruani automatikisht raportet',
    appInfoTitle: 'SEMAFORI',
    appInfoSubtitle: 'Versioni 1.0.0',
    trafficSystemInfo: 'Sistemi i menaxhimit të trafikut',
    accident: 'Aksident',
    construction: 'Punime në rrugë',
    heavyTrafficType: 'Trafik i rëndë',
    weather: 'Mot',
    minor: 'E ulët',
    moderate: 'Mesatare',
    major: 'E lartë',
    role: 'Roli',
    department: 'Departamenti',
    phone: 'Telefoni',
    editProfile: 'Redakto profilin',
    signOut: 'Çkyçu',
    cancel: 'Anulo',
    saveChanges: 'Ruaj ndryshimet',
    notSet: 'Nuk është vendosur',
    trafficOfficer: 'Oficer trafiku',
    supervisor: 'Supervizor',
    manager: 'Menaxher',
    administrator: 'Administrator',
    departmentPlaceholder: 'p.sh. Kontrolli i Trafikut',
    phonePlaceholder: 'Shkruaj numrin e telefonit',
    userDefault: 'Përdorues',
    emailRequired: 'Email-i është i nevojshëm.',
    emailInvalid: 'Shkruaj një adresë email të vlefshme.',
    passwordRequired: 'Fjalëkalimi është i nevojshëm.',
    passwordTooShort: 'Fjalëkalimi duhet të jetë të paktën 6 karaktere.',
    nameRequired: 'Emri i plotë është i nevojshëm.',
    nameTooShort: 'Emri duhet të jetë të paktën 2 karaktere.',
    passwordNeedsLetterAndNumber: 'Përdor të paktën një shkronjë dhe një numër.',
    passwordsDoNotMatch: 'Fjalëkalimet nuk përputhen.',
    aiGreeting: 'Përshëndetje! Unë jam asistenti yt për menaxhimin e trafikut. Mund të analizoj incidentet, të jap rekomandime dhe të përmbledh gjendjen aktuale. Si mund të të ndihmoj?',
    aiNoRecentIncidents: 'Nuk ka incidente të fundit për të dhënë këshilla. Ju lutem krijoni një raport incidenti së pari.',
    aiFeaturesUnavailable: 'Shërbimi AI nuk është i disponueshëm tani. Po jap një përgjigje lokale bazuar në raportet ekzistuese.',
    aiUnknownRequest: 'Mund të të ndihmoj me analizën e trafikut, këshilla për incidentet ose një përmbledhje të raporteve aktuale.',
    aiGenericError: 'Nuk munda të marr përgjigje nga Groq, por po jap një përmbledhje lokale për të të ndihmuar.',
    aiOffline: 'Jeni offline. Kontrolloni lidhjen tuaj të internetit.',
    aiTimeout: 'Kërkesa te AI ka skaduar. Provoni përsëri.',
    aiAuthError: 'Çelësi i Groq nuk është i vlefshëm ose mungon. Shtoni një çelës korrekt për përgjigje live.',
    aiQuickActions: 'Veprimet e shpejta',
    aiAnalyzePatterns: 'Analizo modelet',
    aiAnalyzePatternsPrompt: 'Analizo modelet aktuale të trafikut dhe jep njohuri.',
    aiGetAdvice: 'Merr këshilla',
    aiGetAdvicePrompt: 'Më jep këshilla për trajtimin e incidentit të fundit.',
    aiBestPractices: 'Praktika të mira',
    aiBestPracticesPrompt: 'Cilat janë disa praktika më të mira për menaxhimin e trafikut?',
    aiAskPlaceholder: 'Pyet për menaxhimin e trafikut...',
    noIncidentsOnMap: 'Nuk ka incidente për t’u shfaqur në hartë.',
    createReportToSeeIt: 'Krijo një raport për ta parë këtu.',
    mapClickHint: 'Kliko në hartë për të vendosur pin-in e incidentit.',
    profileUpdated: 'Profili u përditësua me sukses.',
    profileUpdateFailed: 'Përditësimi i profilit dështoi.',
  },
  english: {
    dashboard: 'Dashboard',
    aiAssistant: 'AI Assistant',
    aiAssistantTitle: 'Traffic AI Assistant',
    aiPoweredBy: 'Powered by Groq',
    settings: 'Settings',
    trafficCommandCenter: 'Traffic command center',
    totalReports: 'Total reports',
    totalItems: 'total',
    active: 'Active',
    cleared: 'Cleared',
    underControl: 'Under control',
    reportIncident: 'Incident report',
    createNewTrafficAlert: 'Create a new traffic alert',
    editMode: 'Edit mode',
    newReport: 'New report',
    incidentTitle: 'Incident title',
    enterTitle: 'Road closure on M4',
    category: 'Category',
    description: 'Description',
    addDetails: 'Add details about the incident and recommended response.',
    loginTitle: 'Traffic Command Center',
    loginSubtitle: 'Sign in to manage incident reports and monitor road conditions.',
    loginButton: 'Sign in',
    loginSigningIn: 'Signing in...',
    loginNoAccount: 'New to Traffic Command?',
    loginSignupLink: 'Create an account',
    signupTitle: 'Join the Traffic Command Team',
    signupSubtitle: 'Create a secure account to manage incidents and monitor road conditions.',
    signupButton: 'Create an account',
    signupCreatingAccount: 'Creating account...',
    signupAlreadyHaveAccount: 'Already have an account?',
    signupLoginLink: 'Sign in here',
    close: 'Close',
    fullName: 'Full name',
    email: 'Email',
    emailAddress: 'Email address',
    passwordLabel: 'Password',
    confirmPassword: 'Confirm password',
    tryAgain: 'Try again',
    signupSuccess: 'Account created successfully. Redirecting to login...',
    selectLocation: 'Select a location on the map',
    clickMapToPlacePin: 'Click on the map to place your pin',
    locationSelected: 'Selected location',
    severity: 'Severity',
    status: 'Status',
    addIncident: 'Add incident',
    updateReport: 'Update report',
    cancelEdit: 'Cancel edit',
    recentIncidents: 'Recent incidents',
    reportFlow: 'Report flow',
    noReports: 'No incident reports yet. Use the form to add one and monitor traffic conditions.',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Delete this incident report?',
    titleRequired: 'Title is required.',
    offline: 'You are offline. Check your internet connection and try again.',
    timeout: 'Request timed out. Please try again.',
    networkError: 'Connection problem. Check your internet and try again.',
    successMessage: 'Your report has been recorded successfully.',
    updateSuccess: 'Incident updated successfully.',
    deleteSuccess: 'Incident removed from your dashboard.',
    errorSave: 'Cannot save incident.',
    errorUpdate: 'Cannot update incident in Supabase.',
    errorDelete: 'Cannot delete incident from Supabase.',
    errorFetch: 'Cannot load reports from Supabase.',
    liveTrafficMap: 'Live traffic map',
    currentOperations: 'Current operations',
    trafficOverview: 'Traffic flow overview',
    affectedCorridor: 'Most affected corridor',
    mainIncident: 'Main incident',
    systemHealth: 'System health',
    route: 'Route I-95',
    heavyTrafficDescription: 'Heavy delays due to lane closure and heavy traffic.',
    northHub: 'Accident at North Hub',
    responseTeam: 'Response team deployed. Estimated cleanup in 45 min.',
    stable: 'Stable',
    allSystems: 'All monitoring systems are functioning normally.',
    saving: 'Saving...',
    noDetails: 'No additional details provided.',
    retry: 'Retrying...',
    personalizeExperience: 'Personalize your experience',
    theme: 'Theme',
    light: 'Light',
    lightTheme: 'Light mode',
    dark: 'Dark',
    darkTheme: 'Dark mode',
    language: 'Language',
    albanian: 'Albanian',
    english: 'English',
    notifications: 'Notifications',
    enable: 'Enable',
    disable: 'Disable',
    autoSave: 'Auto-save',
    notificationsInfo: 'Get alerts for new incidents',
    autoSaveInfo: 'Automatically save reports',
    appInfoTitle: 'SEMAFORI',
    appInfoSubtitle: 'Version 1.0.0',
    trafficSystemInfo: 'Traffic management system',
    accident: 'Accident',
    construction: 'Road work',
    heavyTrafficType: 'Heavy traffic',
    weather: 'Weather',
    minor: 'Minor',
    moderate: 'Moderate',
    major: 'Major',
    role: 'Role',
    department: 'Department',
    phone: 'Phone',
    editProfile: 'Edit profile',
    signOut: 'Sign out',
    cancel: 'Cancel',
    saveChanges: 'Save changes',
    notSet: 'Not set',
    trafficOfficer: 'Traffic officer',
    supervisor: 'Supervisor',
    manager: 'Manager',
    administrator: 'Administrator',
    departmentPlaceholder: 'e.g. Traffic Control',
    phonePlaceholder: 'Enter phone number',
    userDefault: 'User',
    emailRequired: 'Email is required.',
    emailInvalid: 'Enter a valid email address.',
    passwordRequired: 'Password is required.',
    passwordTooShort: 'Password must be at least 6 characters.',
    nameRequired: 'Full name is required.',
    nameTooShort: 'Name must be at least 2 characters.',
    passwordNeedsLetterAndNumber: 'Use at least one letter and one number.',
    passwordsDoNotMatch: 'Passwords do not match.',
    aiGreeting: 'Hello! I am your traffic management assistant. I can analyze incidents, provide recommendations, and summarize the current situation. How can I help?',
    aiNoRecentIncidents: 'There are no recent incidents to advise on yet. Please create an incident report first.',
    aiFeaturesUnavailable: 'The AI service is unavailable right now. I will answer locally based on the existing reports.',
    aiUnknownRequest: 'I can help with traffic analysis, incident advice, or a summary of the current reports.',
    aiGenericError: 'I could not get a response from Groq, but I am giving you a local summary to keep you moving.',
    aiOffline: 'You are offline. Check your internet connection.',
    aiTimeout: 'The AI request timed out. Please try again.',
    aiAuthError: 'The Groq API key is missing or invalid. Add a valid key to get live AI responses.',
    aiQuickActions: 'Quick actions',
    aiAnalyzePatterns: 'Analyze patterns',
    aiAnalyzePatternsPrompt: 'Analyze the current traffic patterns and share insights.',
    aiGetAdvice: 'Get advice',
    aiGetAdvicePrompt: 'Give me advice for handling the latest incident.',
    aiBestPractices: 'Best practices',
    aiBestPracticesPrompt: 'What are some best practices for traffic management?',
    aiAskPlaceholder: 'Ask about traffic management...',
    noIncidentsOnMap: 'No incidents to display on the map.',
    createReportToSeeIt: 'Create a report to see it here.',
    mapClickHint: 'Click the map to place the incident pin.',
    profileUpdated: 'Profile updated successfully.',
    profileUpdateFailed: 'Failed to update profile.',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'albanian');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.albanian?.[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
